version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@6
  
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
        #  filters:
        #    branches:
        #      only:
        #        - main
          requires:
            - helm_lint
